require("fleetscut.set")
require("fleetscut.packer")
require("fleetscut.lsp")
require("fleetscut.cmp")
require("fleetscut.telescope")
require("fleetscut.dap")
require("fleetscut.illuminate")
require("fleetscut.tokyonight")

require("fleetscut.keymaps").telescope_keymap(bufnr)
require("fleetscut.keymaps").general_keymap(bufnr)
